### ISSUE TITLE
Not able to see anything under Profiler or Hit counts

### ISSUE THREAD

**Issue by montoyo4me** [ak239/devtools-preprocessor#15]
Hi,

I am not able to see anything under Profiler or Hit counts. I am using latest Chrome version.
Basically I want to find out JS code coverage so thought to try devtools-preprocessor.I am having few FitNesse UI test cases and by executing these in browser I want to find out JS code coverage.I am not sure whether this is possible with devtools-preprocessor or not but wanted to just give it a try.

Please let me know what all steps I need to perform once I install devtools-preprocessor extension.
If there are any other tools/extensions you know please let me know.
Help is deeply appreciated.

![1](https://cloud.githubusercontent.com/assets/10863177/6057577/7ae203f8-ad45-11e4-92db-a3140b9d6be5.png)

**Comment by ak239** [comment]
Hi,

This extension will be supported by current last version of chrome and maybe two next after API which used by this extension will be deprecated. Now I've tested and it works.
You can use next instruction:
1. Open site that you want to inspect.
2. Click first button on extension toolbox and page will be reloaded with patched scripts.
3. Click second button, button will changed its color to red, and recording will started.
4. When you click second button second time - recording stops and you can analyze results.

**Comment by montoyo4me** [comment]
Hi,

Thanks for your reply.
By performing steps mentioned by you still I am not able to see anything.My chrome version is 40.0.2214.
